fipe.api.url=https://fipe.parallelum.com.br/api/v2
quarkus.rest-client.fipe-api.url=${fipe.api.url}

quarkus.rest-client.fipe-api.connect-timeout=5000
quarkus.rest-client.fipe-api.read-timeout=5000


quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/test

quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.redis.devservices.enabled=false

mp.messaging.outgoing.marcas-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.marcas-out.queue.name=marcas
mp.messaging.outgoing.marcas-out.host=rabbitmq
mp.messaging.outgoing.marcas-out.port=5672
mp.messaging.outgoing.marcas-out.username=guest
mp.messaging.outgoing.marcas-out.password=guest

quarkus.redis.hosts=redis://redis:6379
quarkus.http.auth.permission.public.paths=/auth/*,/swagger-ui/*,/q/*
quarkus.http.auth.permission.public.policy=permit

mp.jwt.verify.issuer=fipe-api
mp.jwt.verify.publickey.location=classpath:publicKey.pem
smallrye.jwt.sign.key.location=classpath:privateKey.pk8